---
# CentOS 7 (2vCPU 4GB RAM) (nginx/varnish/php-fpm/mysql/elasticsearch/redis)
#   Memory Allocation
#     512MB Varnish
#     1GB MySQL
#     512MB ElasticSearch
#     1GB Redis
#
#     1GB PHP-FPM (ondemand)
#     1GB PHP cron (ondemand)
varnish_data_storage_size: 512M
mysqld_memory_percentage: 25
es_heap_size: "512m"
redis_obj_maxmem: 768mb
redis_ses_maxmem: 256mb
php_fpm_pm_max_children: 10
mysqld_max_connections: 15


# --- System Configs
syseng_access_users:
  - { username: mjohnson, pubkey: persistent/ssh-keys/matt.johnson }
www_user_ssh_keys:
  - persistent/ssh-keys/matt.johnson

app_domain: stage-do-centos8-min.cldev.io

mysqld_datadir: /data/mysql


# --- Magento Demo Configs
magento_demo_config_overrides:
  MAGENTO_COMPOSER_PROJECT: magento/project-community-edition
  MAGENTO_REL_VER: 2.4.0
  REDIS_OBJ_HOST: "localhost"
  REDIS_OBJ_PORT: "6379"
  REDIS_OBJ_DB: "0"
  REDIS_SES_HOST: "localhost"
  REDIS_SES_PORT: "6380"
  REDIS_SES_DB: "0"
  VARNISH_HOST: "localhost"
  VARNISH_PORT: "6081"
  SEARCH_ENGINE: "elasticsearch7"
  ELASTIC_HOST: "localhost"
  ELASTIC_PORT: "9200"
  ELASTIC_ENABLE_AUTH: "1"
  ELASTIC_USERNAME: "elastic"
  ELASTIC_PASSWORD: "changeme"
  SHOULD_SETUP_TFA: "true"


# --- Tech Stack (Services) Configuration
use_classyllama_repo_ius: false
use_geerlingguy_repo_remi: false
use_classyllama_repo_php_appstream: true
php_stream_version: "7.3"
php_version: 73
php_enablerepo: ""
php_package_name_extra: ""
php_default_modules:
  - bcmath
  - cli
  - common
  - devel
  - fpm
  - gd
  - intl
  - json
  - mbstring
  # - mcrypt      # installed on 7.1 and prior
  # - sodium      # installed on 7.2 and later - Not required - Not included in AppStream
  - mysqlnd
  - opcache
  - pdo
  # - pecl-redis # Not required - Not included in AppStream
  - process
  - soap
  - xml
  - xmlrpc
  # - pecl-zip # Required - Missing in CentoOS 8 AppStream
  - pear # Requirement for PECL
php_additional_modules: []
  # - xdebug
  # - pecl-imagick
php_pecl_software_package_dependencies:
  - libzip
  - libzip-devel
  # - libzstd
  # - libzstd-devel
  # - libsodium
  # - libsodium-devel
php_pecl_packages:
  - pecl/zip
  # - pecl/xdebug
  # - pecl/igbinary
  # - pecl/redis # Does not enable igbinary, lzf, or zstd compression support
  #              # To enable compression support reference: https://gist.github.com/mttjohnson/935c047ba20ed6a79fa5b291e6b85455
  # - pecl/libsodium
php_pecl_extension_ini:
  - dest: /etc/php.d/40-zip.ini
    content: extension=zip.so
  # - dest: "{{ php_xdebug_ini_path }}.disabled"
  #   content: zend_extension=xdebug.so
  # - dest: /etc/php.d/40-igbinary.ini
  #   content: extension=igbinary.so
  # - dest: /etc/php.d/40-redis.ini
  #   content: extension=redis.so
  # - dest: /etc/php.d/40-sodium.ini
  #   content: extension=sodium.so

use_classyllama_repo_python_appstream: true
python3_stream_version: "3.6"
python_module_name: python36
python_package_name: python3
python_software_packages: 
  - "{{ python_package_name }}"
  - "{{ python_package_name }}-pip"
  - "{{ python_package_name }}-devel"
  - "{{ python_package_name }}-PyMySQL"
python_pip_packages:
  - segno # used for generating QR Code images for setting up 2FA OTP Authentication

use_classyllama_mariadb: true
use_classyllama_percona: false
mariadb_version: "10.3"

use_classyllama_repo_varnish: false
use_classyllama_varnish: true
varnish_version: "60lts"

use_classyllama_repo_nginx: false
use_classyllama_repo_nginx_appstream: true
nginx_stream_version: "1.16"
nginx_vhosts:
  - name: "{{ app_domain }}"
    pool: data
    params:
      server_name: "{{ app_domain }}"
      webroot: /var/www/data/current/pub
      proxy_port: 6081
    includes:
      - available.d/magento2-static.conf
nginx_backends:
  - name: www-data
    pool: data
    listen: 8080
    webroot: /var/www/data/current/pub
    includes:
      - default.d/nginx-status.conf
      - available.d/realip.conf
      - available.d/magento2.conf
nginx_extras:
  - { src: nginx/conf.d/default.conf,               dest: conf.d/default.conf }
  - conf.d/map.conf
  - available.d/realip.conf
  - available.d/magento2-static.conf
  - available.d/magento2.conf

use_classyllama_multi_redis: true
redis_package_name: "redis"
redis_enablerepo: ""
redis_version: 50

use_elastic_elasticsearch: true
es_version: 7.8.1


# --- Additional Tools Configuration
use_imagemagick: false
certbot_email: matt.johnson@classyllama.com
certbot_domains:
  - "{{ app_domain }}"
