---

##### ---------------------------
# dev-centos7-transition.lan
##### ---------------------------
# Common on CentOS 7
# Magento 2.3.7
#
# CentOS 7
# PHP 7.3
# Nginx 1.18
# MySQL 5.7
# ElasticSearch 7.x
# Varnish 6.x
# Redis 5.x


# --- System Configs
app_domain: dev-centos7-transition.lan


# --- Magento Demo Install
magento_demo_config_overrides:
  MAGENTO_COMPOSER_PROJECT: magento/project-community-edition
  MAGENTO_REL_VER: "2.3.7"
  MAGENTO_DEPLOY_MODE: "developer"
  MAGENTO_FPC: "redis"
  REDIS_OBJ_HOST: "localhost"
  REDIS_OBJ_PORT: "6379"
  REDIS_OBJ_DB: "0"
  REDIS_SES_HOST: "localhost"
  REDIS_SES_PORT: "6379"
  REDIS_SES_DB: "1"
  REDIS_FPC_HOST: "localhost"
  REDIS_FPC_PORT: "6379"
  REDIS_FPC_DB: "2"
  VARNISH_HOST: "localhost"
  VARNISH_PORT: "6081"
  SEARCH_ENGINE: "elasticsearch7"
  ELASTIC_HOST: "localhost"
  ELASTIC_PORT: "9200"
  ELASTIC_ENABLE_AUTH: "1"
  ELASTIC_USERNAME: "elastic"
  ELASTIC_PASSWORD: "changeme"


# --- Tech Stack (Services) Configuration
use_classyllama_repo_ius: true
use_geerlingguy_repo_remi: false
use_classyllama_repo_php_appstream: false
use_classyllama_repo_php_remi_modular: false
php_version: 73
php_enablerepo: ""
php_package_name_extra: "73"
php_default_modules:
  - bcmath
  - cli
  - common
  - devel
  - fpm
  - gd
  - intl
  - json
  - mbstring
  - mysqlnd
  - opcache
  - pdo
  # - pear # Requirement for PECL
  - pecl-redis # Not required
  - process
  - sodium # Not required
  - soap
  - xml
  - xmlrpc
  # - pecl-zip
php_additional_modules:
  - xdebug
  # - pecl-imagick

use_classyllama_repo_python_appstream: false
python_package_name: python # CentOS 7 uses Python 2.7
python_software_packages: 
  - "{{ python_package_name }}"
  - "{{ python_package_name }}-pip"
  - "{{ python_package_name }}-devel"
  - "MySQL-python" # Python 2.7 MySQL library package

use_classyllama_mariadb: false
use_classyllama_percona: true
percona_version: 57

use_classyllama_repo_varnish: true
use_classyllama_varnish: true
varnish_version: 64

use_classyllama_repo_nginx: true
use_classyllama_repo_nginx_appstream: false
nginx_stream_version: "1.18"

use_classyllama_multi_redis: true
redis_package_name: "redis5"
redis_enablerepo: "ius-archive"
redis_version: 50

use_elastic_elasticsearch: true
es_version: 7.12.1


# --- Additional Tools Configuration
use_create_www_projects_dir: false
