version: '3'
services:
  app:
    build: .
    env_file: .env
    ports:
      - "80:5000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    restart: always
  redis:
    image: redis:6.0
    env_file: .env
    ports:
      - "6379:6379"
  db:
    image: postgres:12.5
    env_file: .env
    ports:
      - "5432:5432"