version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - .:/var/app
    env_file: .env
  db:
    image: postgres:alpine
    env_file: .env
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"