---

##### ---------------------------
# dev-laravel.lan
##### ---------------------------
# Latest on CentOS 8
# Laravel
#
# CentOS 8
# PHP 7.4
# Nginx 1.18
# MariaDB 10.3
# ElasticSearch 7.x
# Redis 5.x


# --- System Configs
app_domain: dev-laravel.lan
app_root_dir: /var/www/data
app_root_install_dir: "{{ app_root_dir }}/laravel"
database_create_user: laravel_user
database_create_db: laravel_db


# --- Laravel Demo Configs
laravel_demo_hostname: "{{ app_domain }}"


# --- Tech Stack (Services) Configuration
use_classyllama_repo_ius: false
use_geerlingguy_repo_remi: true
use_classyllama_repo_php_appstream: false
use_classyllama_repo_php_remi_modular: true
php_stream_version: "remi-7.4"
php_version: 74
php_enablerepo: ""
php_package_name_extra: ""

php_default_modules:
  - bcmath
  - cli
  - common
  - devel
  - fpm
  - gd
  - intl
  - json
  - mbstring
  # - mcrypt      # installed on 7.1 and prior
  - sodium      # installed on 7.2 and later
  - mysqlnd
  - opcache
  - pdo
  - pecl-redis5 # Not required
  - process
  - soap
  - xml
  - xmlrpc
  - pecl-zip
  - pear # Requirement for PECL
php_additional_modules:
  - xdebug
  # - pecl-imagick

use_classyllama_repo_python_appstream: true
python3_stream_version: "3.6"
python_module_name: python36
python_package_name: python3
python_software_packages: 
  - "{{ python_package_name }}"
  - "{{ python_package_name }}-pip"
  - "{{ python_package_name }}-devel"
  - "{{ python_package_name }}-PyMySQL"

use_classyllama_mariadb: true
use_classyllama_percona: false
mariadb_version: "10.3"

use_classyllama_repo_varnish: false
use_classyllama_varnish: false

use_classyllama_repo_nginx: true
use_classyllama_repo_nginx_appstream: false
nginx_stream_version: "1.18"
nginx_vhosts:
  - name: "{{ app_domain }}"
    pool: data
    params:
      server_name: "{{ app_domain }}"
      webroot: "{{ app_root_dir }}/current/public"
      #proxy_port: 6081
      proxy_port: 8080
    includes: []
nginx_backends:
  - name: www-data
    pool: data
    listen: 8080
    webroot: "{{ app_root_dir }}/current/public"
    includes:
      - default.d/nginx-status.conf
      - available.d/realip.conf
      - available.d/laravel-app.conf
nginx_extras:
  - available.d/realip.conf
  - { src: ../persistent/templates/nginx/conf.d/map.conf, dest: conf.d/map.conf }
  - { src: ../persistent/templates/nginx/available.d/laravel-app.conf, dest: available.d/laravel-app.conf }

use_classyllama_multi_redis: true
redis_package_name: "redis"
redis_enablerepo: ""
redis_version: 50

use_elastic_elasticsearch: true
es_version: 7.8.1


# --- Additional Tools Configuration
use_classyllama_n98_magerun: false
use_classyllama_magento_demo: false
use_current_to_app_install_symlink: true
use_create_www_projects_dir: false
use_create_www_app_install_dir: true
